### ISSUE TITLE
Source returned by server is not translated

### ISSUE THREAD

**Issue by Senne** [pmachaux/angular-universal-i18n-demo#1]
As already mentioned in [a comment](https://medium.com/@JanBranny/im-not-quite-sure-if-this-is-right-solution-if-you-inspect-view-source-http-localhost-4200-fr-e4bbc14444b) on your Medium article, the content returned by the server isn't translated.

Steps to reproduce:

- `npm run dev:ssr`
- Visit `view-source:http://localhost:4200/fr/` in Chrome
- “_App container_” instead of “_Conteneur de l'application_”

**Comment by pmachaux** [comment]
Hi Senne,
Thanks, I now understand better the comment on Medium.
Indeed you are right, the `view-source` only has “App container”. I would have expected the HTML returned by my server to return the translated string.
I took a look at this dist file and found this (dist\angular-universal-i18n-demo\browser\fr\main.js):
```
if (typeof ngI18nClosureMode !== "undefined" && ngI18nClosureMode) {
    const MSG_EXTERNAL_appContainer$$SRC_APP_APP_COMPONENT_TS_1 = goog.getMsg("App container");
    I18N_0 = MSG_EXTERNAL_appContainer$$SRC_APP_APP_COMPONENT_TS_1;
}
else {
    I18N_0 = "Conteneur de l'application";
}
```
and this
```
var I18N_0;
if (typeof ngI18nClosureMode !== "undefined" && ngI18nClosureMode) {
    const MSG_EXTERNAL_fistpage$$SRC_APP_FIRST_PAGE_COMPONENT_TS_1 = goog.getMsg("My first page");
    I18N_0 = MSG_EXTERNAL_fistpage$$SRC_APP_FIRST_PAGE_COMPONENT_TS_1;
}
else {
    I18N_0 = "Ma premi\xE8re page";
}
```
I cannot say for sure. But it seems that neither in JIT nor AOT builds the HTML pre-filled.
The script linked the source, get the message in the HTML, and replace it with the proper value.
This is why if we remove the view source and use the app the regular way, the content is translated.
I don't see this as an issue as it is Angular handling all of this and the end result is the same.

What's your opinion on this?

**Comment by Senne** [comment]
Hi Pierre, thanks for the fast response. The whole concept of Angular Universal is to have statically generated source code, so crawlers such as search engines or social networks, that typically can't see dynamically injected content from single page applications, can also index the pages. In your app’s case, crawlers will always see the English content, regardless of the chosen language.

**Comment by pmachaux** [comment]
You are right. I tested to use localization in the title and meta description and the issue remains.
I will need to investigate more but it seems that the Angular build is forcing that, not sure how we can get a workaround...

**Comment by pmachaux** [comment]
I created an issue on the Angular Universal repo: https://github.com/angular/universal/issues/1789
We'll see if there is an actual solution, I cannot find any on my side

**Comment by pmachaux** [comment]
@Senne , after the angular team answered to me, I have the solution. 
Basically, we need to also localize the server build.
The issue with that is that it creates 2 folders (fr and en) so server.ts cannot be used as proxy to run both languages.
So for dev mode, I keep as is. But for production mode, I localize the server bundle to have the expected behavior. I added `proxy-server.js` file that is used only in production to run both /fr and /en at the same time.
I'll update my article shortly (the source code is already updated). 

Thanks for helping to see the issue!
